config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
  resources :users
  resources :movies, only: [:index, :show]
  resources :my_list, only: [:index]
  resources :comments_admin, only: [:index]
  resources :comments, only: [:create]
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  get '/favorites' => 'favorites#add'
  delete '/favorites' => 'favorites#remove'
  delete '/comments_admin' => 'comments_admin#remove'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_and_belongs_to_many :movies
    belongs_to :user, :optional => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_and_belongs_to_many :movies
    belongs_to :user, :optional => true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_and_belongs_to_many :favorites
    has_and_belongs_to_many :comments 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :presence => true, :uniqueness => true
    has_many :favorites
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present?
    end
  
    # Check if the user is admin or not
    def check_for_login
      redirect_to login_path unless @current_user.present?
    end
    
    # Function to check if the user is signed in or not
    def check_for_admin
      redirect_to root_path unless @current_user.present? && @current_user.admin?
    end
    
end

app/controllers/comments_admin_controller.rb
class CommentsAdminController < ApplicationController
  before_action :check_for_login, :only => [:index]

  def index
    @comments = Comment.all
  end

  # Removing comments by admin
  def remove
    comment = Comment.all.find_by(params[:id])
    comment.delete
    redirect_back :fallback_location => comments_admin_index_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_for_login

  # Creating comments by users
  def create
    comment = Comment.new comment_params
    @current_user.comments << comment
    redirect_back :fallback_location => movies_path
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :title)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :check_for_login

  # Liking a movie and adding it to your favorite list
  def add
    favorite = Favorite.new :movie_title => params["movie_title"]
    @current_user.favorites << favorite
    redirect_back :fallback_location => movies_path
  end

  # Disliking a movie and removing it from your favorite list
  def remove
    fav = Favorite.find_by(:movie_title => params["movie_title"])
    @current_user.favorites.destroy fav.id
    redirect_back :fallback_location => movies_path
  end

  private
  def favorite_params
    params.require(:favorite).permit(:movie_title, :user_id)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  # Finding a move by title name which is a primary key in this API
  def index
    @movies = get_data_by_title(params[:title])
  end


  def show
    @movie = get_movie_by_title(params[:id])
    if @current_user.present?
      # Check for favorite situation
      @liked = @current_user.favorites.exists?(:movie_title => @movie["Title"]) 
    end
    # Adding Comment
    @comment = Comment.new
    # Reading all of the comments
    @comments = Comment.all.where(:title => params["id"])
    @users = User.all
  end

  def movie_params
    params.require(:movie).permit(:title, :year, :rate, :image)
  end

  private

  # JSON Parsing
  def get_data_by_title(title)
    response = HTTParty.get("http://www.omdbapi.com/?apikey=#{Rails.application.secrets.omdbKey}&s=#{title}")
    response.parsed_response['Search']
  end

  def get_movie_by_title(title)
    response = HTTParty.get("http://www.omdbapi.com/?apikey=#{Rails.application.secrets.omdbKey}&t=#{title}")
    response.parsed_response
  end
end

app/controllers/my_list_controller.rb
class MyListController < ApplicationController
  before_action :check_for_login, :only => [:index]

  def index
    @list = @current_user.favorites
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  # Login by controlling all errors.
  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  # Sign up 
  def create
    @user = User.new user_params
    if @user.save # returns truthy on success
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments_admin/index.html.erb
<h1 class="yllw">All Comments</h1>

<%# Showing all of the comments for admin %>
<% @comments.each do |c| %>
  <div class="inline_block cBox">
    <p class="yllw"><%= c.title %></p>
    <p class="yllw"><%= c.content %></p>
    <%= link_to "Delete", comments_admin_index_path(c.id), :method => "delete" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<%# Navigation for the website. %>

<nav class="bg-dark">
    <%= link_to 'Home', root_path, class: "badge badge-ligh" %>
    <div>
        <% if @current_user.present? %>
            <% if @current_user.admin? %>
                <%= link_to 'All users', users_path, class: "badge badge-ligh" %>
                <%= link_to "Comments", comments_admin_index_path, class: "badge badge-ligh" %>
            <% end %>
            <%= link_to "My List", my_list_index_path, class: "badge badge-ligh" %>
            <%= link_to "Log out #{ @current_user.email }", login_path, :method => 'delete', class: "badge badge-ligh" %>
        <% else %>
            <%= link_to 'Sign up', new_user_path, class: "badge badge-ligh" %>
            <%= link_to 'Sign in', login_path, class: "badge badge-ligh" %>
        <% end %>
    </div>
</nav>
<br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<%# Showing all related movies after searching for a name. %>

<% if @movies.present? && @movies != "N/A" %>
  <% @movies.each do |movie| %>
    <% if movie["Poster"].present? && movie["Poster"] != "N/A" %>
      <%=link_to image_tag(movie["Poster"], :class => 'thumb border'), movie_path(movie["Title"]) %>
    <% end %>
  <% end %>
<% else %>
  <h2 class="td centre"><%= "Sorry! Could not find #{params[:title]}." %><h2>
<% end %>

app/views/movies/show.html.erb
<%# Showing movie page %>
<div>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-10">
              <% if @movie["Poster"].present? && @movie["Poster"] != "N/A" %>
                <%= image_tag @movie["Poster"], class: "movieImage" %>
              <% end %>
              <% if @current_user.present? %>
                <% if @liked %>
                  <%= link_to image_tag("like.png", :alt => "favorite", :class => "favIcon"), {:controller => "favorites", :action => "remove", :movie_title => @movie["Title"] }, :method => "delete" %>
                <% else %>
                  <%= link_to image_tag("dislike.png", :alt => "favorite", :class => "favIcon"), {:controller => "favorites", :action => "add", :movie_title => @movie["Title"] } %>
                <% end %>
              <% end %>
              <div class="star-rating"></div>
              <div class="table-responsive">
                <table class="table">
                <tbody>
                  <tr>
                    <td class="td"><strong>Title:</strong></td>
                    <td class="td"><%= @movie["Title"] %></td>
                  </tr>
                  <tr>
                    <td class="td"><strong>Year:</strong></td>
                    <td class="td"><%= @movie["Year"] %></td>
                  </tr>
                  <tr>
                    <td class="td"><strong>Rating:</strong></td>
                    <td class="td"><%= @movie["imdbRating"] %></td>
                  </tr>
                </tbody>
                </table>
              </div>
              <div class="td"><%= @movie["Plot"] %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="td col-sm-5" >
      <%# Showing all available comments for the movie. %>
      <div>
        <% if @comments.present? %>
          <% @comments.each do |c| %>
            <%= label("", @users.find_by(id: "#{c.user_id}").email, :class =>"strong comments") %>
            <br/>
            <%=  label("", c.content, :class =>"comments")  %>
            <br/><br/>
          <% end %>
        <% end %>
      </div>
      <%# Adding new comment for the movie if you are signed in. %>
      <% if @current_user.present? %>
        <%= form_for @comment do |f| %>
          <%= f.label :Comments %>
          <%= f.text_area :content, class: "commentBox form-control", rows: "5", maxlength: "250" %>
          <%= f.hidden_field :title, value: @movie["Title"] %>
          <%= f.submit %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/my_list/index.html.erb
<h1 class="yllw">My list</h1>

<%# Showing all of the user favorite list. %>
<% @list.each do |movie| %>
  <div class="inline_block">
    <%=link_to movie.movie_title, movie_path(movie.movie_title) %>
  </div>
<% end %>

app/views/pages/home.html.erb
<%# Home page %>
<h1 class="yllw home">IMDB</h1>
<p class="yllw home">Enter movie name:</p>

<%# Searching for movie name %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<div class="contain">
  <br/>
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <form class="card card-sm" action="/movies">
        <div class="card-body row no-gutters align-items-center">
          <div class="col-auto">
            <i class="fas fa-search h4 text-body"></i>
          </div>
          <%= form_tag(movies_path, method: "get") do %>
            <div class="col">
              <%= text_field_tag 'q', nil, class: 'form-control mr-sm-2', placeholder: 'Search Movie ...', name: 'title' %>
            </div>
            <div class="col-auto">
              <%= submit_tag "Search", :id => "submit-button", :class => "btn btn-outline-success my-2 my-sm-0" %> 
            </div>
          <% end %>   
        </div>
      </form>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<%# Sign in page. %>
<div id="login">
  <div class="logContainer">
    <div id="login-row" class="row justify-content-center align-items-center">
      <div id="login-column" class="col-md-6">
        <div id="login-box" class="col-md-12">
          <form id="login-form" class="form" action="" method="post">
            <h3 class="text-center text-info">Login</h3>
            <%= form_tag login_path do%>
              <div class="form-group">
                <label for="username" class="text-info">Username:</label><br>                
                <%= email_field_tag :email, "", :class => 'form-control' %>
              </div>
              <div class="form-group">
                <label for="password" class="text-info">Password:</label><br>
                <%= password_field_tag :password, "", :class => 'form-control' %>
              </div>
              <div class="form-group">
                <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                <%= submit_tag "Sign in", :class => "btn btn-info btn-md" %>
              </div>              
              <div id="register-link" class="text-right">
                <a href="users/new" class="text-info">Register here</a>
              </div>
            <% end %>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<%# Controlling errors. %>
<% if flash[:error].present? %>
  <h2 class="yllw"><%= flash[:error] %></h2>
<% end %>

app/views/users/index.html.erb
<h1 class="yllw">All Users</h1>

<%# Showing all users for admin and accessibility to remove them. %>
<% @users.each do |user| %>
  <div class="inline_block">
    <p class="yllw"><%= user.email %></p>
    <%= link_to 'Delete user', user, :method => 'delete', :class => "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/users/new.html.erb
<%# Sign up page and controlling if there is any error. %>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="yllw"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div id="signup">
    <div class="logContainer">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <h3 class="text-center text-info">Sign up</h3>
                    <%= form_for @user do |f| %>
                        <div class="form-group">
                            <label for="username" class="text-info">Username:</label><br>                    
                            <%= f.email_field :email , :class => 'form-control' %>
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-info">Password:</label><br>
                            <%= f.password_field :password, :class => 'form-control' %>
                        </div>
                        <div class="form-group">
                            <label for="password" class="text-info">Confirm Password:</label><br>
                            <%= f.password_field :password_confirmation, :class => 'form-control' %>
                        </div>
                        <%= f.submit "Sign up", :class => "btn btn-info btn-md" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>